// Generated by Wrangler by running `wrangler types --include-runtime=false`
declare namespace Cloudflare {
  interface Env {
    USER_OBJECT: DurableObjectNamespace<import("./src/durable_objects/UserObject").UserObject>;
    SESSION_OBJECT: DurableObjectNamespace<import("./src/durable_objects/SessionObject").SessionObject>;
  }
}
interface Env extends Cloudflare.Env {}